name: ssl_cli
description: A flutter architecture creator package.
version: 3.0.2
homepage: https://github.com/AscEmon/SSL_CLI

environment:
  sdk: '>=2.15.1 <4.0.0'


dependencies:
  args: ^2.3.0
  path: ^1.8.2
  

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  ssl_cli:
