name: ssl_cli
description: A simple command-line application to generate SSL template (folder and file structure) for Flutter Applications
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
#   path: ^1.8.0
  args: ^2.3.0
  license: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
